version: '3.6'
services:
  database:
    image: postgres:11
    restart: always
    networks:
      - kong-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
       - postgres-db:/data/postgres
  
  migration:
    image: kong/kong-gateway:3.4.1.1
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    command: kong migrations bootstrap
    depends_on:
      - database

  kong:
    image: kong/kong-gateway:3.4.1.1
    restart: always
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    depends_on:
      - database

  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    ports:
      - 1337:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_URI=postgres://kong:kongpass@database:5432/kong
    depends_on:
      - database

  nginx-proxy:
    image: nginx:latest
    restart: always
    networks:
      - kong-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - kong

  insert-data:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - kong-net
    depends_on:
      - kong


volumes:
  postgres-db:
    driver: local

networks:
  kong-net: